### ISSUE TITLE
DSY - Q6 - bugs

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#13]
- [x] => réalisez le code selon le cavena fournis - voir issue #8 
- [x] => variable VS tableau => selon le cdc est-ce qu'on vous dit que `frame` est un tableau ? 
- [x] => variable => comment déclarez-vous des variables ?

**Comment by Z1nghy** [comment]
La cdc me dit que frame est une variable de 32 bits
![image](https://github.com/user-attachments/assets/6714c920-7aa6-4354-83e5-1cb6064f3c72)

**Comment by PBYetml** [comment]
@Z1nghy que vous dit la consignes ici : voir issue #8 -> est-ce que votre développement respect ce qui est demandé ?! -> réponse, non => vous devez implémenté votre solution dans une solution finale !!!
