### ISSUE TITLE
LCX - Q6 - bugs

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#15]
- [x] => réalisez le code selon le cavena fournis - voir issue #8 
- [x] => CDC => est-ce que le CDC vous demande de retourner un ou des valeurs ? 
- [x] => instruction => avec le mot clé `return` pouvez-vous retourner plusieurs variables ?

**Comment by REXI38** [comment]
CDC : il nous ais pas demandé de retourner des valeurs.
instruction : non il n'est possible de retourner une seul variable.
