### ISSUE TITLE
ARD - Q6 - bugs

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#17]
- [ ] => réalisez le code selon le cavena fournis - voir issue #8 
- [x] => CDC => en faisant des instructions => est-ce que vous répondez au CDC 
- [x] => opérateur et constante => décalage `<<` à gauche ? pourquoi ?, que représente la constante numérique après ?

**Comment by Alex84628** [comment]
est-ce que vous répondez au CDC ? non il ne falait pas les calculer

**Comment by PBYetml** [comment]
voir commentaire de la pull request #37
