### ISSUE TITLE
ARD - Q3 - Bugs et amélioration 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#19]
- [x] => réaliser le correction du structogramme NSI selon les indications sur l'issue #18 
- [ ] => constante VS variable => pour vous quelle est la différence ?
- [ ] => variable => comment déclarez-vous une variable non entière ? qu'est-ce que cela peut être ?
- [ ] => spécification CDC => itération => en NSI comment pouvez-vous représenter une itération toutes les minutes 
- [x] => spécification CDC => instruction => comment pouvez représentez un delta de température ? 
- [x] => algorithme => comment représentez-vous un clignotement en instruction ? ou quelle autre possibilité avez-vous de représentez ceci 
- [x] => algorithme => même remarque ci-dessus pour la notion d'activation 
- [x] => algorithme => test / condition => pour déterminer le clignotement (alarme) -> faut vraiment deux conditions ?  
- [x] => algorithme => test / condition => alarme active => pouvez-vous regrouper deux tests successif en un seul ?
- [x] => algorithme => test / condition => chauffage active => ne faut-il pas rajouter une 3ème condition 
- [x] => algorithme => test / condition => chauffage active => même remarque que ci-dessus

**Comment by Alex84628** [comment]
constante = la valeurs ne change jamais  
variable = la valeurs est variable

**Comment by Alex84628** [comment]
variable non entier = float

**Comment by Alex84628** [comment]
delta température = température max - température min

**Comment by Alex84628** [comment]
clignotement = 
allumé alarme
délais
éteindre alarme
délais

**Comment by Alex84628** [comment]
pour déterminer le clignotement (alarme) -> faut vraiment deux conditions ? oui car il faut que le capteur fonctionne entre sa température max et min et que elle s'allume à -10 degré

**Comment by Alex84628** [comment]
alarme active => pouvez-vous regrouper deux tests successif en un seul ? non car pas le même capteur le capteur intérieur pourrait fonctionner alors que celui à l'extérieur non

**Comment by Alex84628** [comment]
chauffage active => ne faut-il pas rajouter une 3ème condition ? oui pour l'éteindre

**Comment by Alex84628** [comment]
chauffage active => même remarque que ci-dessus. Pour la ventilation aussi oui

**Comment by PBYetml** [comment]
Ne respectez pas le nouveau CDC -> format du rendu du flow char !!!

**Comment by PBYetml** [comment]
après quelques itérations, vous avez réussi à répondre à tous les critères demandés...
