### ISSUE TITLE
LCX - Q3 - Bugs et amélioration 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#21]
- [x] => réaliser le correction du structogramme NSI selon les indications sur l'issue #18 
- [ ] => constante => comment faites-vous pour éviter le hardcodage ?
- [ ] => variable => comment définissez-vous une variable ? 
- [ ] => spécification CDC => itération => en NSI comment pouvez-vous représenter une itération toutes les minutes 
- [x] => spécification CDC => instruction => comment pouvez-vous représenter un delta de température ? 
- [ ] => spécification CDC => capteur => quelles sont les sous-routines ou instruction pour obtenir la température extérieur et/ou intérieur
- [ ] => algorithme => test / condition => alarme active => pouvez-vous regrouper deux tests successif en un seul ?
- [ ] => algorithme => test / condition => que représente la notion d'indice ? 
- [ ] => algorithme => test / condition => chauffage active => ne faut-il pas rajouter une 3ème condition 
- [ ] => algorithme => test / condition => ventilation active => même remarque que ci-dessus

**Comment by REXI38** [comment]
comment faites-vous pour éviter le hardcodage ?
en utilisant une macro la valeur seras stockée a un seul endroits et seras réutilisé plusieurs fois

comment définissez-vous une variable ?
pour définir une variable on doit lui donner un type et un nom, exemple :  int8_t temperature

en NSI comment pouvez-vous représenter une itération toutes les minutes
en utilisant un timer qui attend 60 secondes a la fin d'une boucle sans fin

comment pouvez-vous représenter un delta de température ?
on soustrais la valeur de la température extérieur a celle de l'intérieur cela nous donne un delta

quelles sont les sous-routines ou instruction pour obtenir la température extérieur et/ou intérieur
pour la valeur de la température extérieur il faut récupérer la tension du capteur et multiplié ça valeur pas la pente calculée selon le delta de température sur le delta de tension sans oublié le downset de -50°C
Pour le capteur intérieur la valeur nous est directement donné sur 8 bit 7 de data 1 bit de signe il faut uniquement soustrais 2^7 a la valeur reçu si le huitième bit est a 1

pouvez-vous regrouper deux tests successif en un seul ?
oui avec un OU regroupant les deux condition qui résulte au même résultat

que représente la notion d'indice ?
si toutes les condition pour l'alarme l'indice vaux 3 et la dernière condition (si indice ==3)  l'alarme s'éteint (implémentation différente pour le nouveau structogramme car pas pratique)

chauffage active / ventilation active =>  ne faut-il pas rajouter une 3ème condition
oui il faut considéré la température extérieur

**Comment by REXI38** [comment]
![Structogramme](https://github.com/user-attachments/assets/23a27271-52f1-45a4-a7b0-d2a2e1bfe10e)
[ThermostaAuto.pdf](https://github.com/user-attachments/files/17818111/ThermostaAuto.pdf)

**Comment by REXI38** [comment]
je parle pas d'interruption je vois pas de quoi vous parler, la fonction de clignotement et fait avec le bloque "alarmeled = ON" chaque minute elle change d'état

pour le le capteur intérieur la valeur et directement donnée sur une résolution de 1°C par bit il n'y a pas d'autre conversion a faire

![image](https://github.com/user-attachments/assets/f80a6b08-3477-4fd1-b621-f5b0405f70a9)

**Comment by PBYetml** [comment]
- [ ] => pull request => dépôt => je ne vois pas vos dernière modification => mettre à jour votre dépôt 
- [ ] => remarque générale => clarté de lecture => généralement on va mettre les constantes au début et après on définit les variables 
- [ ] => itération => sous routine d'attente => algorithme => est-ce que c'est une bonne pratique ? 
- [ ] => instruction => algorithme => est-ce que vous pouvez calculer la température si vous n'avez pas encore lu le capteur ? 
- [ ] => instruction => quelle différence entre `capteurInt` et `tempInt` => n'y a-t-il pas un process entre les deux ? 
- [ ] => algorithme => gestion alarme => clignotement => pensez-vous que votre principe de clignotement et optimal ? 
- [ ]

**Comment by PBYetml** [comment]
Suite à la discussion et aux corrections => issues fermées !!! Bisous
