### ISSUE TITLE
RBN - Q3 - Bugs et amélioration

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#22]
- [ ] => réaliser le correction du structogramme NSI selon les indications sur l'issue #18 
- [ ] => constante => comment représentez-vous des constantes sous un structogramme 
- [ ] => variable => comment définissez-vous une variable ? 
- [ ] => spécification CDC => itération => en NSI comment pouvez-vous représenter une itération toutes les minutes 
- [ ] => spécification CDC => instruction => comment pouvez représentez un delta de température ? 
- [ ] => instruction / sous-routine / fonction => en NSI, comment pouvez-vous représenter un appel de fonction (sous-routine) 
- [ ] => spécification CDC => capteur => quelles sont les sous-routines ou instruction pour obtenir la température extérieur et/ou intérieur
- [ ] => algorithme => test / condition => alarme - chauffage - ventilation => pour activer ou non des ces 3 éléments qu'avez-vous besoin de d'implémenter dans votre structogramme ?

**Comment by Renato1226** [comment]
ma correction a été envoyé
