### ISSUE TITLE
KGR - Q3 - Bugs et amélioration

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#28]
- [x] => réaliser le correction du structogramme NSI selon les indications sur l'issue #18 
- [x] => constante => comment pourriez-vous faire pour éviter le hardcodage ?
- [x] => constante => comment définissez-vous des constantes dans un structogramme ? 
- [x] => variable => comment définissez-vous une variable génériquement, que doit connaître un développeur pour instancier une variable
- [x] => spécification CDC => itération => en NSI comment est représenté une itération ? (design) et comment la définissez-vous ? 
- [x] => spécification CDC => capteur => quelles sont les sous-routines ou instruction pour obtenir la température extérieur et/ou intérieur ? est-ce que vos sous-routine fonctionne pour le deux capteurs ? 
- [x] => algorithme => test / condition => alarme clignote - active => pourquoi faire que le delta de température soit prioritaire par rapport aux autres tests ? que vous dit le CDC ? 
- [x] => spécification CDC => algorithme => test / condition VS itération => chauffage - ventilation => même remarque ci-dessus 
- [x] => algorithme => test / condition => chauffage active => ne faut-il pas rajouter une 3ème condition 
- [x] => algorithme => test / condition => ventilation active => même remarque que ci-dessus

**Comment by Kazanaris** [comment]
4) Il y a plusieurs types d'itérations : 
a) La while (1) aussi appelée "Endless loop", c'est une itération qui effectuer le programme dans la boucle puis, une fois à la fin de celui-ci, revenir au début de la boucle et effectuer à nouveau le programme et ce à l'infini.
b) La while (expression) aussi appelée " TANQUE.... FAIRE", c'est une itération qui effectue le programme tant que l'expression entre parenthèses est vraie.
c) La Do...... While (expression) aussi appelée "REPETER ....JUSQUE'A" ou "REPETER....TANTQUE", c'est une itération qui effectue le programme tant que l'expression entre parenthèses est vraie. La différence entre celle-ci et celle du point b) est que celle-ci fait le test de l'expression à la fin de la boucle tandis que celle du point b) le fait au début de la boucle.
d) La FOR aussi appelée "POUR....FAIRE", c'est une itération qui nous permet d'initialiser une expression, la tester puis de l'incrémenter ou de la décrémenter avant le début de chaque boucle. Le programme dans la boucle est effectuer tant que le résultat du test est vrai. 
Exemple : for (x = 2; x < 28; x++)
               {
                 printf("Hello World");
               }

Pour leurs représentations dans un NSI, voir les images que j'ai mis en annexes dans le dossier "Correction Q3".

**Comment by Kazanaris** [comment]
5) Pour obtenir les températures intérieur et extérieur j'ai, dans la correction, fait en sorte que chaque capteur ai une fonction qui va lire le capteur et la valeur lue est mise dans une variable. Une fonction converti la valeur de la variable en degré. Ensuite la valeur en degré est mis dans une autre variable. Il est important que chaque capteurs aies leurs sous-routines personnelles étant donné que l'un des capteurs donne les informations relatives à la température en tension et l'autre capteur les donnes en binaire.

**Comment by Kazanaris** [comment]
6) Le test du delta de température n'est PAS prioritaire par rapport aux autres tests. Le CdC dit clairement que c'est selon les valeurs de températures (en degrés) que les alarmes, la ventilation et le chauffage seront activé.

**Comment by PBYetml** [comment]
Ou se trouve votre structogramme complet -> par rapport à votre pull request #35 ?

**Comment by Kazanaris** [comment]
Sous "Test1_KGR" j'ai crée un dossier appeler "Correction Q3", j'espère que vous pouvez y accéder. Autrement j'ai juste oublié de faire un .PNG. J'ai crée un document appeler "Correction_Q3.PNG".
