### ISSUE TITLE
HMT - Q6 - bugs

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#7]
- [ ] => réalisez le code selon le cavena fournis - voir issue #8 
- [x] => convertir votre structogramme en code -> langage C 
- [ ] => variable VS tableau ? définition ? 
- [ ] => que signifie pour vous un sous-routine ? 
- [ ] => que veut dire pour la notion de de corps d'une fonction ? 
- [ ] => pourquoi une boucle ? 
- [ ] => comment sélectionnée les données ? 
- [ ] => est-ce que le structogramme correspond au CDC

**Comment by HENRIIIIIIIII** [comment]
Trouvé :D

**Comment by PBYetml** [comment]
vous ne respectez pas le point suivant : 

- [ ] => copier les fichiers sources se trouvant dans ce dépôt : [fichiers sources pour correctifs Q6](https://github.com/PBYetml/PROG_SLO1_24_25/tree/main/SourcesPourCorrections) -> si vous êtes malin, ces fichiers sont facilement utilisable ;) 

vous devez utiliser 3 fichiers sources comme demandé de le point ci-dessus !!!
