### ISSUE TITLE
KGR - Q6 - bugs 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG__RESULTAS_ETUDIANTS_TEST1_SLO1_24_25#9]
- [x] => réalisez le code selon le cavena fournis - voir issue #8 
- [x] => variable locale => ou doit-on les déclarer 
- [x] => constante => écriture en hexa => 0xFFFF => représentation de la valeur max ? est-ce que cela représente une valeur de 32bits

**Comment by Kazanaris** [comment]
1) Les variables locales doivent être déclarées dans la fonction où elles sont être utilisées.
2)La valeur maximale de 0xFFFF en décimale est de 65'535. Cela ne représente PAS une valeur de 32bit mais une valeur de 16 bits.
   La valeur de 32 bits Hexadécimale est 0xFFFFFFFF.
